COS301-SE-2022/ReverseHand

.github/workflows/android.yml
.github/workflows/index.yml

**Note**: Assuming my assumption that the app we run will always be in apps/app then this will work.
It is very minimal, makes use of zero cache and not that efficient but that can be dealt with later. I thought linting and executing tests rather important now. Will see when to add build

CI to execute and analyze code

---

.github/workflows/android.yml
.github/workflows/index.yml
README.md
apps/app/pubspec.lock

Requirements badge requires write access from organization  so I cant add that one from now.
Code coverage badge will come soon hopefully.

Added CI Tests badge for Build quality badge 

---

.github/workflows/android.yml
apps/app/android/build.gradle

Take note of modification in build.gradle file. Due to an error similar to this: 
Now this is just for Android. No idea how I am gonna build the app bundle for ios but will make a plan. As long as we have something in the meantime

Added build app bundle

---

apps/app/lib/main.dart
apps/app/pubspec.lock
apps/app/pubspec.yaml
libs/example/.gitignore
libs/example/.metadata
libs/example/CHANGELOG.md
libs/example/LICENSE
libs/example/README.md
libs/example/analysis_options.yaml
libs/example/lib/example.dart
libs/example/project.json
libs/example/pubspec.yaml
libs/example/test/example_test.dart
libs/redux/.gitignore
libs/redux/.metadata
libs/redux/CHANGELOG.md
libs/redux/LICENSE
libs/redux/README.md
libs/redux/analysis_options.yaml
libs/redux/lib/app_state.dart
libs/redux/lib/reducers/reducer.dart
libs/redux/lib/redux.dart
libs/redux/project.json
libs/redux/pubspec.yaml
libs/redux/test/redux_test.dart
workspace.json

New library was generated for the redux design pattern as well as an example library

✨ Added classes and functions required for redux

---

apps/app/lib/main.dart
apps/app/test/widget_test.dart
libs/example/lib/example.dart
libs/example/pubspec.yaml
libs/redux_comp/lib/actions/actions.dart
libs/redux_comp/lib/app_state.dart
libs/redux_comp/lib/redux_comp.dart

Added more of the skeleton code for redux as well as added the store to the default app.

:construction: Further redux implementation

---

.github/workflows/android.yml
.github/workflows/full.yml
.github/workflows/index.yml
README.md

*Code coverage to come
*added badge for libraries.io
*added cache

CI_CD branch

---

.github/workflows/android.yml
apps/app/project.json
libs/example/project.json
libs/general/project.json
libs/redux_comp/project.json
merge-reports.js

Will add badge to readme once this works

Attempt to see if CodeCov works

---

libs/example/lib/example.dart
libs/general/test/general_test.dart

This will be fixed later but until more code is added mock tests are neccessary

:white_check_mark: Added mock test to general to pass CI/CD check

---

apps/app/lib/main.dart
libs/example/lib/example.dart
libs/redux_comp/lib/actions/actions/example_action.dart
libs/redux_comp/lib/app_state.dart
libs/redux_comp/lib/reducers/reducer.dart
libs/redux_comp/lib/reducers/reducers/example_reducer.dart

Added mock code to give an example on how to add all the necessary components to the redux pattern.

:clown_face: Redux

---

README.md
libs/consumer/project.json
libs/consumer/test/consumer_test.dart

I am just putting the badge in the readme
I still cant figure out why its only picking up example lib

✅ Added mock test to pass CI/CD

---

libs/amplify/.vscode/settings.json

Modified app_state to confirm to async_redux and deleted reducers folder

:recycle: App now conforms to async_redux

---

libs/general/test/general_test.dart

Login page successfully tested

✅ Added widget test for login page

---

.github/workflows/android.yml
execute_script.js
merge-reports.js

I think it is worth adding this. 
From my fork it seems the removal of the mock tests is improving something. So don't know maybe with time it will get better. This is better than the time when it was just picking up example lib only . Though please merge my other PR first.
And promise to sort out the Readme in the morning. Know I am the only one left but as you can tell from the time of this PR I might be still not awake early morning. If you could just do those redux tests I would happy. My commits are in a decent spot now I think

✅ Update the codecov setup

---

libs/tradesman/project.json
libs/tradesman/test/tradesman_test.dart

Consumer Done
General Done
Tradesman Done
Michael you mind doing the Redux one? that didn't look nice. My commits have gone up to a decent spot

✅ Added TradesmanJobListings Widget Test

---

libs/consumer/lib/methods/populate_job_details.dart
libs/consumer/lib/methods/populate_job_listings.dart
libs/consumer/lib/pages/job_details.dart
libs/redux_comp/lib/app_state.dart

When you click on an advert, it will take you to a job details page that will be populated based on the state of the advert clicked on. 
Closes #101

✨(Consumer): job_details.dart dynamically created from job_listing.dart Inkwell onclick

---

libs/consumer/test/consumer_test.dart

1. Please wait whilst I link Issue to this
2. This is a nice test to demo because I discovered there is this thing called debugPrint so I actually say what I do and this test is good because we are actually entering input into textfields whilst testing which is a plus. So I think favour this one when demoing. The tests will get better as I learn new stuff

Changed the Consumer tests to  match new changes

---

.github/workflows/index.yml

Those skipped tests in the PR were just annoying me. Just decided to get rid of them

🎨 Removed Dead Code

---

.github/workflows/android.yml

I am not a 100% sure what format that exclude thing takes in nx but hopefully I did it right

⚡️ Attempt to exclude amplify folder from analyser

---

.github/workflows/android.yml

Sorry I should have read you message, just pushed merge for some stupid reason. Updated command seems to leave out amplify project

🐛 Corrected command to exclude amplify

---

libs/authentication/lib/methods/populate_login.dart
libs/authentication/lib/methods/populate_sign_up.dart
libs/authentication/lib/pages/login.dart
libs/authentication/lib/widgets/button.dart
libs/authentication/lib/widgets/link.dart
libs/authentication/lib/widgets/otp_pop_up.dart
libs/authentication/lib/widgets/textfield.dart
libs/authentication/test/authentication_test.dart
libs/consumer/lib/methods/populate_job_details.dart
libs/consumer/test/consumer_test.dart
libs/general/lib/widgets/dialog_helper.dart
libs/general/lib/widgets/pop_up.dart
libs/redux_comp/lib/actions/init_amplify_action.dart
libs/redux_comp/lib/actions/login_action.dart
libs/redux_comp/lib/actions/view_bids_action.dart
libs/tradesman/lib/pages/job_details.dart
libs/tradesman/lib/pages/job_listings.dart
libs/tradesman/lib/tradesman.dart
libs/tradesman/lib/widgets/place_bid_popup.dart
libs/tradesman/lib/widgets/rating_popup.dart
libs/tradesman/lib/widgets/rating_stars.dart
libs/tradesman/pubspec.yaml
libs/tradesman/test/tradesman_test.dart

Merge the tradesman branch into develop with updates made to the signup page, implemented shared popup widget, and implemented unstyled OTP, Bid Placing, and Tradesman Rating popups. Also fixed untracked .gitingore files.

🔀 💄 Merge Tradesman branch with popup implementation

---

.github/aws/buildspec.yml
execute_script.js

🐛 Fixing indentation error

---

libs/redux_comp/lib/actions/edit_advert_action.dart
libs/redux_comp/lib/models/advert_model.dart

**Question**: from lines 43-53 is there perhaps a better way to do that logic?

Added editAdvert reducer

---

apps/app/android/build.gradle

Updated build.gradle to allow app to run on android devices and emulators.

🐛 Fix build.gradle file for android

---

apps/app/lib/main.dart
libs/chat/lib/pages/chat_selection_page.dart
libs/chat/pubspec.yaml
libs/consumer/lib/pages/advert_details_page.dart
libs/consumer/lib/pages/consumer_listings_page.dart
libs/consumer/lib/pages/consumer_profile_page.dart
libs/consumer/lib/pages/create_new_advert_page.dart
libs/consumer/lib/pages/view_bids_page.dart
libs/consumer/lib/widgets/radio_select_widget.dart
libs/general/lib/widgets/job_card.dart
libs/general/lib/widgets/navbar.dart
libs/geolocation/lib/pages/custom_location_search_page.dart
libs/redux_comp/lib/actions/adverts/create_advert_action.dart
libs/redux_comp/lib/actions/adverts/view_jobs_action.dart
libs/redux_comp/lib/actions/bids/set_active_bid_action.dart
libs/redux_comp/lib/models/advert_model.dart
libs/tradesman/lib/pages/advert_details.dart
libs/tradesman/lib/pages/bid_details_page.dart
libs/tradesman/lib/pages/edit_bid_page.dart
libs/tradesman/lib/pages/edit_profile_page.dart
libs/tradesman/lib/pages/tradesman_listings.dart
libs/tradesman/lib/pages/tradesman_profile_page.dart
libs/tradesman/lib/pages/view_bids_page.dart
libs/tradesman/lib/widgets/navbar.dart
libs/tradesman/lib/widgets/quick_view_bid.dart

Cara's updates for tradesman
I integrated Cara's radio button
Cara was experiencing git bugs so I just pulled her code and made a PR off my branch

(💄Refactor & Tradesman) 

---

libs/amplify/amplify/backend/api/reversehandapi/schema.graphql
libs/amplify/amplify/backend/function/deleteChatResolver/deleteChatResolver-cloudformation-template.json
libs/amplify/amplify/backend/function/deleteChatResolver/src/index.js
libs/amplify/amplify/backend/function/editUserDetailResolver/src/index.js
libs/amplify/amplify/backend/function/viewJobsResolver/src/index.js
libs/amplify/amplify/team-provider-info.json
libs/redux_comp/lib/actions/user/edit_user_details_action.dart

(🐛Refactor)

---

apps/app/lib/main.dart
libs/consumer/lib/pages/edit_profile_page.dart
libs/redux_comp/lib/actions/geolocation/set_place_action.dart
libs/redux_comp/lib/actions/user/user_table/check_user_exists_action.dart
libs/redux_comp/lib/actions/user/user_table/edit_user_details_action.dart
libs/tradesman/lib/pages/edit_profile_page.dart
libs/tradesman/lib/pages/tradesman_profile_page.dart
libs/tradesman/lib/widgets/multiselect_widget.dart

Signup & edit profile works again
close #407

(♻️ Auth) : signup works again

---

libs/admin/lib/pages/admin_advert_details_page.dart
libs/chat/lib/pages/chat_page.dart
libs/consumer/lib/pages/advert_details_page.dart
libs/consumer/lib/pages/view_bids_page.dart
libs/general/lib/widgets/bottom_sheet.dart
libs/general/lib/widgets/quick_view_job_card.dart
libs/redux_comp/lib/app_state.dart
libs/redux_comp/lib/models/advert_model.dart
libs/tradesman/lib/pages/advert_details.dart
libs/tradesman/lib/pages/edit_profile_page.dart
libs/tradesman/lib/pages/tradesman_profile_page.dart
libs/tradesman/lib/pages/view_bids_page.dart
libs/tradesman/lib/widgets/multiselect_widget.dart

Signing up a user no longer crashes when pressing on the field a second time
Signup now has input validation
Signup now displays error messages

:ambulance: Amplify

---

apps/app/pubspec.lock
libs/admin/lib/pages/admin_content_page.dart
libs/admin/lib/pages/admin_metrics_page.dart
libs/admin/lib/pages/admin_users_page.dart
libs/amplify/.gitignore
libs/authentication/lib/methods/validation.dart
libs/authentication/lib/pages/login_page.dart
libs/authentication/lib/pages/signup_page.dart
libs/authentication/lib/widgets/auth_textfield_light.dart
libs/authentication/lib/widgets/forgot_password_popups/email_popup_widget.dart
libs/authentication/lib/widgets/forgot_password_popups/new_password_popup_widget.dart
libs/authentication/lib/widgets/forgot_password_popups/otp_popup_widget.dart
libs/authentication/lib/widgets/link_widget.dart
libs/chat/lib/pages/chat_page.dart
libs/chat/lib/pages/chat_selection_page.dart
libs/chat/lib/widgets/action_bar_widget.dart
libs/chat/lib/widgets/action_button_widget.dart
libs/chat/lib/widgets/chat_appbar_widget.dart
libs/chat/lib/widgets/quick_view_chat_widget.dart
libs/consumer/lib/pages/consumer_listings_page.dart
libs/consumer/lib/pages/consumer_profile_page.dart
libs/consumer/lib/pages/create_new_advert_page.dart
libs/consumer/lib/pages/edit_advert_page.dart
libs/general/lib/pages/activity_stream.dart
libs/general/lib/widgets/hint_widget.dart
libs/general/lib/widgets/loading_widget.dart
libs/tradesman/lib/pages/tradesman_listings.dart
libs/tradesman/lib/pages/tradesman_profile_page.dart

* Chat UI Fixes
* Made HintWidget dynamic
* Forgot Password popups
* Fixed loaders

(Refactor): UI Updates

---

libs/authentication/lib/pages/login_page.dart
libs/authentication/lib/pages/signup_page.dart
libs/authentication/lib/pages/usertype_selection_page.dart
libs/authentication/lib/widgets/circle_blur_widget.dart
libs/authentication/lib/widgets/divider_widget.dart
libs/authentication/lib/widgets/forgot_password_popups/email_popup_widget.dart
libs/authentication/lib/widgets/forgot_password_popups/new_password_popup_widget.dart
libs/authentication/lib/widgets/forgot_password_popups/otp_popup_widget.dart
libs/authentication/lib/widgets/otp_pop_up.dart
libs/authentication/lib/widgets/transparent_divider.dart
libs/chat/lib/pages/chat_page.dart
libs/chat/lib/pages/chat_selection_page.dart
libs/chat/lib/widgets/chat_appbar_widget.dart
libs/chat/lib/widgets/date_label_widget.dart
libs/chat/lib/widgets/quick_view_chat_widget.dart
libs/consumer/lib/pages/advert_details_page.dart
libs/consumer/lib/pages/bid_details_page.dart
libs/consumer/lib/pages/consumer_listings_page.dart
libs/consumer/lib/pages/edit_advert_page.dart
libs/general/lib/pages/archived_advert_details_page.dart
libs/general/lib/widgets/notification_card_widget.dart
libs/general/lib/widgets/quick_view_bid.dart
libs/general/lib/widgets/quick_view_job_card.dart
libs/tradesman/lib/pages/advert_details.dart
libs/tradesman/lib/pages/bid_details_page.dart
libs/tradesman/lib/pages/domain_confirmation_page.dart
libs/tradesman/lib/pages/tradesman_listings.dart
libs/tradesman/lib/pages/tradesman_profile_page.dart
libs/tradesman/lib/pages/view_bids_page.dart
libs/tradesman/lib/widgets/quick_view_bid_widget.dart

- Made ratings box pressable
- Fixed padding and overflowing
- refactored notification card
- fix view quote button functionality

(Refactor): UI Changes

---

libs/chat/lib/widgets/quick_view_chat_widget.dart
libs/consumer/lib/pages/consumer_profile_page.dart
libs/consumer/lib/pages/create_new_advert_page.dart
libs/general/lib/widgets/quick_view_job_card.dart
libs/tradesman/lib/pages/advert_details.dart
libs/tradesman/lib/pages/tradesman_profile_page.dart
libs/tradesman/lib/widgets/upload_bid_widgets/edit_bid_sheet.dart
libs/tradesman/lib/widgets/upload_bid_widgets/upload_bid_amount_sheet.dart

Padding fixes for Usability testing
(@caaaramia the date to quick view job cards can be added back just removed them for user testing until it is scalable to all phones)

Tradesman UI overflow fixes

---

libs/authentication/lib/pages/login_page.dart
libs/authentication/lib/widgets/forgot_password_popups/new_password_popup_widget.dart
libs/consumer/lib/pages/bid_details_page.dart
libs/consumer/lib/pages/create_new_advert_page.dart
libs/consumer/lib/widgets/accept_bid_popup.dart
libs/tradesman/lib/pages/limited_tradesman_profile_page.dart
libs/tradesman/lib/widgets/upload_bid_widgets/upload_bid_amount_sheet.dart

- fixed toast messages
- general padding fixes
- linked reviews to limited tradesman profile

(Refactor): UI Fixes
